from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AUTO_SEARCH_REWARD_TITLE = Button(area={'cn': (334, 149, 369, 165), 'en': (334, 149, 369, 165), 'jp': (334, 149, 369, 165), 'tw': (334, 149, 369, 165)}, color={'cn': (182, 193, 204), 'en': (182, 193, 204), 'jp': (182, 193, 204), 'tw': (182, 193, 204)}, button={'cn': (334, 149, 369, 165), 'en': (334, 149, 369, 165), 'jp': (334, 149, 369, 165), 'tw': (334, 149, 369, 165)}, file={'cn': './assets/cn/azur_stats/AUTO_SEARCH_REWARD_TITLE.png', 'en': './assets/cn/azur_stats/AUTO_SEARCH_REWARD_TITLE.png', 'jp': './assets/cn/azur_stats/AUTO_SEARCH_REWARD_TITLE.png', 'tw': './assets/cn/azur_stats/AUTO_SEARCH_REWARD_TITLE.png'})
