name: 仅同步 master 到 Gitee
on:
  workflow_run:
    workflows: ["全自动整体同步"]
    types:
      - completed
  workflow_dispatch:

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取 master 分支代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: 仅同步 master 到 Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:t717796163/AzurPilot.git"
          destination-repo: "git@gitee.com:t717796163/AzurPilot.git"
          force: true
          refspec: "refs/heads/master:refs/heads/master"
