name: Sync to Gitee
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync GitHub -> Gitee (master 分支)
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/t717796163/AzurPilot
          dst: gitee/t717796163/AzurPilot
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          force_update: true
          # 只同步 master 分支
          branch_white_list: "master"
